In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


• To - Do - 1:
1. Read and Observe the Dataset.
2. Print top(5) and bottom(5) of the dataset {Hint: pd.head and pd.tail}.
3. Print the Information of Datasets. {Hint: pd.info}.
4. Gather the Descriptive info about the Dataset. {Hint: pd.describe}
5. Split your data into Feature (X) and Label (Y).

In [4]:
import pandas as pd
data =pd.read_csv("/content/drive/MyDrive/DATASET/student.csv")

print("Top 5 rows of the dataset:")
print(data.head())

print("\nBottom 5 rows of the dataset:")
print(data.tail())

print("\nDataset Info:")
print(data.info())

print("\nDescriptive Statistics:")
print(data.describe())

# Split the dataset into Features (X) and Labels (Y)
X = data[['Math', 'Reading']]
Y = data['Writing']

# Print the feature and label data
print("\nFeature Data (X):")
print(X.head())

print("\nLabel Data (Y):")
print(Y.head())


Top 5 rows of the dataset:
   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62

Bottom 5 rows of the dataset:
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB
None

Descriptive Statistics:
              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60

• To - Do - 2:

In [5]:
import numpy as np
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/DATASET/student.csv")

X = data[['Math', 'Reading']].values  # Feature Matrix
Y = data['Writing'].values

X_transposed = X.T

print("Feature Matrix (X):")
print(X)
print("\nTransposed Feature Matrix (X.T):")
print(X_transposed)
print("\nTarget Vector (Y):")
print(Y)

W = np.random.rand(X.shape[1])

print("\nWeight Matrix (W):")
print(W)

Y_pred = np.dot(W, X_transposed)

print("\nPredicted Values (Y_pred):")
print(Y_pred)

Feature Matrix (X):
[[48 68]
 [62 81]
 [79 80]
 ...
 [89 87]
 [83 82]
 [66 66]]

Transposed Feature Matrix (X.T):
[[48 62 79 ... 89 83 66]
 [68 81 80 ... 87 82 66]]

Target Vector (Y):
[ 63  72  78  79  62  85  83  41  80  77  64  90  45  77  70  46  76  44
  85  72  53  66  75  49  84  83  68  66  77  78  74  83  72  65  46  66
  50  79  68  46  86  70  61  53  72  75  50  77 100  81 100  87  78  48
  50  44  48  43  67  78  58  91  92  78  42  85  73  83  61  58  60  55
  48  62  68  59  62  48  74  63  80  79  73  79  45  67  89  77  81  88
  53  68  79  77  63  73  60  67 100  79  26  51  80  57  41  78  68  49
  76  41  71  77  89  86  55  80  56  74  85  80  73  74  86  56  53  44
  41  59  71  81  74  78  67  53  56  75  82  79  99  76  59  96  75  61
  56  88  65 100  79  55  61  83  74  59  54  47  82  74  59  74  84  59
  43  65  61  78  84  73  73  92  63  72  61  59  70  87  78  65  73  62
  69  55  73  63  67  86  78  85  83  80  60  90  56  70  55  80  82  60
  78  76  94

• To - Do - 3:
1. Split the dataset into training and test sets.
2. You can use an 80-20 or 70-30 split, with 80% (or 70%) of the data used for training and the rest
for testing.

In [6]:
from sklearn.model_selection import train_test_split
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/DATASET/student.csv")

X = data[['Math', 'Reading']]
Y = data['Writing']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("Shape of X_train (Features for Training):", X_train.shape)
print("Shape of X_test (Features for Testing):", X_test.shape)
print("Shape of Y_train (Target for Training):", Y_train.shape)
print("Shape of Y_test (Target for Testing):", Y_test.shape)

print("\nFirst 5 rows of Training Features (X_train):")
print(X_train[:5])

print("\nFirst 5 rows of Training Targets (Y_train):")
print(Y_train[:5])


Shape of X_train (Features for Training): (800, 2)
Shape of X_test (Features for Testing): (200, 2)
Shape of Y_train (Target for Training): (800,)
Shape of Y_test (Target for Testing): (200,)

First 5 rows of Training Features (X_train):
     Math  Reading
29     64       82
535    62       70
695    36       21
557    81       70
836    82       86

First 5 rows of Training Targets (Y_train):
29     78
535    67
695    25
557    71
836    87
Name: Writing, dtype: int64


Step -2- Build a Cost Function:

In [7]:
import numpy as np

def cost_function(X, Y, W):
    """
    Calculate the Mean Squared Error (MSE) for linear regression.

    Parameters:
    X: np.ndarray - Feature matrix.
    Y: np.ndarray - Target vector.
    W: np.ndarray - Weight vector.

    Returns:
    float - The cost (MSE).
    """
    n = len(Y)  # Number of samples
    Y_pred = np.dot(X, W)  # Predicted values
    cost = (1 / (2 * n)) * np.sum((Y_pred - Y) ** 2)  # MSE formula
    return cost

# Test the cost function with sample data
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

# Calculate the cost
cost = cost_function(X_test, Y_test, W_test)
print("Cost:", cost)


Cost: 0.0


Step -3- Gradient Descent for Simple Linear Regression:


In [9]:
def gradient_descent(X, Y, W, alpha, iterations):
    """
    Perform gradient descent to optimize the parameters of a linear regression model.

    Parameters:
    X (numpy.ndarray): Feature matrix (m x n).
    Y (numpy.ndarray): Target vector (m x 1).
    W (numpy.ndarray): Initial guess for parameters (n x 1).
    alpha (float): Learning rate.
    iterations (int): Number of iterations for gradient descent.

    Returns:
    tuple: A tuple containing the final optimized parameters and the history of cost values.
    """
    m = len(Y)  # number of samples
    cost_history = []

    for _ in range(iterations):
        Y_pred = X.dot(W)  # predicted values
        loss = Y_pred - Y  # difference between predicted and actual
        gradient = (1 / m) * X.T.dot(loss)  # gradient calculation
        W -= alpha * gradient  # update weights
        cost = cost_function(X, Y, W)  # calculate cost
        cost_history.append(cost)  # store cost history

    return W, cost_history

np.random.seed(0)
X = np.random.rand(100, 2)
Y = np.random.rand(100, 1)
W = np.random.rand(2, 1)

alpha = 0.01
iterations = 1000

final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)
print("Final Parameters:", final_params)
print("Cost History:", cost_history)


Final Parameters: [[0.44044412]
 [0.46329667]]
Cost History: [0.14660222125987915, 0.14559739250130407, 0.14460408845943903, 0.14362217675920552, 0.14265152654634444, 0.14169200846994356, 0.1407434946651655, 0.1398058587361739, 0.13887897573925595, 0.13796272216613892, 0.13705697592749816, 0.13616161633665466, 0.13527652409346005, 0.13440158126836665, 0.1335366712866802, 0.13268167891299418, 0.13183649023580252, 0.13100099265228907, 0.13017507485329222, 0.1293586268084416, 0.12855153975146635, 0.12775370616567144, 0.1269650197695815, 0.12618537550274903, 0.12541466951172592, 0.12465279913619645, 0.12389966289526878, 0.12315516047392504, 0.12241919270962603, 0.12169166157907058, 0.12097247018510665, 0.12026152274379294, 0.11955872457160915, 0.11886398207281311, 0.11817720272694329, 0.11749829507646484, 0.11682716871455737, 0.11616373427304348, 0.1155079034104555, 0.1148595888002397, 0.11421870411909585, 0.11358516403545055, 0.11295888419806367, 0.11233978122476483, 0.11172777269131982, 

Step 4: Evaluate the Model
Implementing RMSE Function
Implementing R² Function

In [18]:
def rmse(Y, Y_pred):
    """
    Calculate the Root Mean Square Error (RMSE).

    Parameters:
    Y (numpy.ndarray): Actual target values.
    Y_pred (numpy.ndarray): Predicted target values.

    Returns:
    float: The RMSE value.
    """
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

def r2(Y, Y_pred):
    """
    Calculate the R-squared value.

    Parameters:
    Y (numpy.ndarray): Actual target values.
    Y_pred (numpy.ndarray): Predicted target values.

    Returns:
    float: The R-squared value.
    """
    ss_res = np.sum((Y - Y_pred) ** 2)  # Sum of squared residuals
    ss_tot = np.sum((Y - np.mean(Y)) ** 2)  # Total sum of squares
    return 1 - (ss_res / ss_tot)

print("RMSE:", rmse(Y, Y_pred))
print("R²:", r2(Y, Y_pred))

RMSE: 73.39084313513128
R²: -59181847.32829826


Step -5- Main Function to Integrate All Steps:

In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

def main():
    # Step 1: Load the dataset
    data = pd.read_csv("/content/drive/MyDrive/DATASET/student.csv")

def rmse(Y, Y_pred):
    """Calculate the Root Mean Square Error (RMSE)."""
    return np.sqrt(np.mean((Y - Y_pred) ** 2))

def r2(Y, Y_pred):
    """Calculate the R-squared value."""
    ss_res = np.sum((Y - Y_pred) ** 2)  # Sum of squared residuals
    ss_tot = np.sum((Y - np.mean(Y)) ** 2)  # Total sum of squares
    return 1 - (ss_res / ss_tot)

def gradient_descent(X, Y, W, alpha, iterations):
    """Perform gradient descent to learn weights."""
    n = len(Y)
    cost_history = []

    for _ in range(iterations):
        Y_pred = X.dot(W)
        cost = (1 / (2 * n)) * np.sum((Y_pred - Y) ** 2)  # Mean Squared Error
        cost_history.append(cost)

        gradient = (1 / n) * X.T.dot(Y_pred - Y)  # Gradient
        W -= alpha * gradient  # Update weights

    return W, cost_history

def main():
    # Load the dataset
    data = pd.read_csv("/content/drive/MyDrive/DATASET/student.csv")

    # Split the data into features (X) and target (Y)
    X = data[['Math', 'Reading']].values
    Y = data['Writing'].values.reshape(-1, 1)

    # Check for NaN values in the dataset
    if np.any(np.isnan(X)) or np.any(np.isnan(Y)):
        print("Data contains NaN values. Please clean the dataset.")
        return

    # Normalize the features
    scaler = StandardScaler()
    X = scaler.fit_transform(X)

    # Add bias term to feature matrix
    X = np.hstack((np.ones((X.shape[0], 1)), X))

    # Initialize weights with small random values
    W = np.random.rand(X.shape[1], 1) * 0.01

    # Set hyperparameters
    alpha = 0.001  # Reduced learning rate
    iterations = 1000

    # Train the model using gradient descent
    final_params, cost_history = gradient_descent(X, Y, W, alpha, iterations)

    # Make predictions
    Y_pred = X.dot(final_params)

    # Evaluate the model
    model_rmse = rmse(Y, Y_pred)
    model_r2 = r2(Y, Y_pred)

    print("Final Parameters:", final_params)
    print("Cost History:", cost_history[-5:])
    print("RMSE:", model_rmse)
    print("R²:", model_r2)

if __name__ == "__main__":
    main()



Final Parameters: [[43.38675105]
 [ 5.13466913]
 [ 7.22723725]]
Cost History: [339.2698259097862, 338.61567645440743, 337.9628474511243, 337.31133620476504, 336.66114002575]
RMSE: 25.923435583659806
R²: -1.8958517353696194
